#:schema https://json.schemastore.org/any.json

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#059669"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[client]
toolbarMode = "minimal"